<h1>About</h1>
<p>Number Picture is a web application that enables you to come up with, easily create, and share fresh and interesting tools for visualizing data - that others can then use to visualize their own data.</p><p>These tools we call templates and they take in anybody else's data, shake it around a bit, add some sugar and spice, and then output it structured in a certain way in the form of a picture that hopefully is nice to look at, keeps the viewer engaged, and provides a refreshing change to all the millions and billions of bar graphs and pie charts that we see in our everyday lives.</p><p>
We provide you with the tools to easily create your own templates and it is our wish to make it as easy as possible for you to do this.
All templates that are created are free for anyone to use and all Number Pictures made are freely available for anybody to view.</p>
<br />
<div id="why"><h1>Why?</h1></div>
<p>To illustrate why: let us consider the Pie Chart. Today, the Pie Chart is such a common-place thing that apart from boring us to bits and putting us to sleep during lectures and presentations, it is pretty hard to imagine ever being without. We see it everywhere we go.</p><p>
But, in 1801, William Playfair invented it. Yes, that's right, he invented the Pie Chart. Now, apart from raising the question of what it must be like to live in a world where nobody has ever conceived of a pie chart, this story also raises the question of what other types of charts / graphs / visualizations there are out there that haven't even been thought of yet.</p><p>
So we, here at Number Picture, try to provide some sort of tool for people to start sharing ideas and inspiration with each other in a concrete way about ways in which data can be visualized and organized visually.</p><p>The ball is now in your court - as the Designer.</p>
<p>There are many individuals and organizations out there creating bespoke custom-made visualizations and infographics in isolation (take a look at our <a href="<?php echo $base_url; ?>user/inspiration">INSPIRATION PAGE</a>) - that are interesting and beautiful to look at - but nowhere can we create these ourselves. Number Picture aims to solve this problem.</p>
<p>The quantity of information that we are being bombarded with everyday is only increasing. And as communicators it is becoming more and more difficult to be heard through the information overload.</p><p>People do not want to expend effort trying to understand communications and therefore the communications themselves need to be the ones making the effort. They need to have aesthetic appeal as well as well thought out structure, that is resonant with the data structures being displayed.</p>
<p>We hope you like and can find a good use for the application. For questions and comments contact us <a href="http://numberpicture.com/user/contact">HERE</a>.</p>
